=== NaPrado/XML/Fligth.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="flight">
        <xsd:complexType> 
            <xsd:sequence>
                <xsd:element name="departure" type="xsd:date"/>
                <xsd:element name="passengers">
                    <xsd:complexType>
                        <xsd:sequence minOccurs="3" maxOccurs="unbounded">
                            <xsd:element name="person">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="name" type="xsd:string"/>
                                        <xsd:element name="seat">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="number">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:integer">
                                                                <xsd:minInclusive value="0"/>
                                                                <xsd:maxInclusive value="45"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                                                    <xsd:element name="position">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:maxLength value="1"/>
                                                                <xsd:minLength value="1"/>
                                                                <xsd:pattern value="[A-F]"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="telephone">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="([0-9]{2}(-[0-9]{4}){2}|[0-9]{4}-[0-9]{4})"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="specialFood" minOccurs="0" type="xsd:string"/>
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:ID" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="code" type="xsd:ID" use="required"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== NaPrado/XML/flight.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flight code="LA4554" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./Fligth.xsd">
    <departure>2010-06-01</departure>
    <passengers>
        <person id="ARG1">
            <name>Gustavo Yoshizaki</name>
            <seat>
                <number>6</number>
                <position>F</position >
            </seat>
            <telephone>15-5555-5555</telephone>
        </person>
        <person id="ARG2">
            <name>Silvia Gomez</name>
            <seat>
                <number>30</number>
                <position>A</position>
            </seat>
            <telephone>15-5555-4444</telephone>
        </person>
        <person id="ARG3">
            <name>BanÌƒos Gabriel</name>
            <seat>
                <number>17</number>
                <position>B</position>
            </seat>
            <telephone>5555-3333</telephone>
            <specialFood>Only vegetables</specialFood>
        </person>
    </passengers>
</flight>
