=== NaPrado/XML/pelicula.dtd
<!ELEMENT pelicula (#PCDATA|titulo|estreno|actores|director)*>
<!ATTLIST pelicula identif ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT estreno (#PCDATA)>
<!ELEMENT actores (actor+)*>
<!ELEMENT director (nombre,fechaNacimiento,salario)>
<!ELEMENT actor (nombre,fechaNacimiento,salario,personaje)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT salario (#PCDATA)>
<!ELEMENT personaje (#PCDATA)>
<!ATTLIST salario moneda CDATA #REQUIRED>

=== NaPrado/XML/peli0.xml
<!DOCTYPE pelicula SYSTEM "pelicula.dtd">
<pelicula identif="peli001">
    <titulo>Batman, La Pelicula</titulo>
    <estreno>1966-07-30</estreno>
    <director>
        <nombre>Leslie H.Martinson</nombre>
        <fechaNacimiento>1915-01-16</fechaNacimiento>
        <salario moneda="USD">200000.2</salario>
    </director>
    <actores>
        <actor>
            <nombre>Adam West</nombre>
            <fechaNacimiento>1928-09-19</fechaNacimiento>
            <salario moneda="USD">100000</salario> 
            <personaje>Batman</personaje>
        </actor>
        <actor>
            <nombre>Burt Ward</nombre>
            <fechaNacimiento>1945-07-06</fechaNacimiento>
            <salario moneda="USD">50000.75</salario>
            <personaje>Robin</personaje>
        </actor>
    </actores>
</pelicula>

=== NaPrado/XML/peli1.xml
<!DOCTYPE pelicula SYSTEM "pelicula.dtd">
<pelicula identif="peli001">
    <titulo>Iron Man</titulo>
    <estreno>2008-04-30</estreno>
    <actores>
        <actor>
            <nombre>Robert Downey Jr.</nombre>
            <fechaNacimiento>1965-04-04</fechaNacimiento>
            <salario moneda="USD">500000</salario>
            <personaje>Ironman</personaje>
        </actor>
    </actores>
    <director>
        <nombre>Jon Favreau</nombre>
        <fechaNacimiento>1966-10-19</fechaNacimiento>
        <salario moneda="USD">115000000</salario>
    </director>
</pelicula>
